import { Navigation } from "@/components/navigation";
import { SiteFooter } from "@/components/site-footer";
import { Button } from "@/components/ui/button";
import { StatCard } from "@/components/ui/stat-card";

const stats = [
  { icon: "🌱", label: "Active growers", value: "2,480", detail: "+12% this month" },
  { icon: "🧺", label: "Produce matched", value: "82 tonnes", detail: "Across 14 crop categories" },
  { icon: "📍", label: "Delivery routes", value: "36", detail: "Optimized for today" }
];

export default function Home() {
  return <main id="top"><Navigation />
    <section className="overflow-hidden"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:py-24 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div className="max-w-2xl"><p className="eyebrow">The farm-to-market network</p><h1 className="mt-5 text-5xl font-semibold tracking-tight text-leaf-900 sm:text-6xl">Better value from every harvest.</h1><p className="mt-6 text-lg leading-8 text-stone-600">KisanFlow connects farmers, FPOs, and buyers directly—using smarter demand and supply signals to get fresh produce where it needs to go.</p><div className="mt-8 flex flex-wrap gap-3"><Button>Explore the network <span aria-hidden>→</span></Button><Button variant="secondary">I&apos;m a buyer</Button></div><div className="mt-12 flex items-center gap-3 text-sm text-stone-500"><div className="flex -space-x-2"><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-cream bg-amber-100">👩🏽‍🌾</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-cream bg-green-100">👨🏾‍🌾</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-cream bg-orange-100">🧑🏽‍🌾</span></div>Growing together with farmers across India</div></div><div className="relative grid place-items-center"><div className="absolute h-72 w-72 rounded-full bg-leaf-100 blur-3xl" /><div className="relative w-full max-w-md rounded-[2rem] border border-white/80 bg-white p-6 shadow-soft"><div className="rounded-2xl bg-leaf-700 p-6 text-white"><p className="text-sm text-leaf-100">Today&apos;s harvest forecast</p><p className="mt-2 text-3xl font-semibold">Strong demand for onions</p><div className="mt-5 flex items-end gap-2" aria-label="Demand chart">{[42, 58, 46, 72, 63, 88, 96].map((height, i) => <span key={i} className="w-full rounded-t bg-leaf-100/80" style={{ height: `${height / 2}px` }} />)}</div></div><div className="mt-5 flex items-center justify-between"><div><p className="text-sm font-semibold">Market match found</p><p className="mt-1 text-xs text-stone-500">Pune • 240 kg • Pickup tomorrow</p></div><span className="rounded-full bg-leaf-50 px-3 py-1 text-sm font-semibold text-leaf-700">₹ 28/kg</span></div></div></div></div></section>
    <section id="for-farmers" className="bg-white py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="eyebrow">A clear view of the network</p><div className="mt-3 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="section-title max-w-xl">Make confident decisions, from farm to buyer.</h2><a className="text-sm font-semibold text-leaf-700 hover:text-leaf-900" href="#how-it-works">See how it works →</a></div><div className="mt-10 grid gap-4 md:grid-cols-3">{stats.map(stat => <StatCard key={stat.label} {...stat} />)}</div></div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-16 sm:py-20 lg:px-8"><div className="rounded-3xl bg-earth px-6 py-12 text-white sm:px-12"><p className="eyebrow !text-amber-200">Less waste, more opportunity</p><div className="mt-5 grid gap-10 lg:grid-cols-2"><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">Fresh produce should not get lost in the middle.</h2><div className="space-y-5 text-stone-100"><p>From demand forecasting to route optimization, KisanFlow keeps the whole journey visible and moving.</p><div className="grid gap-3 sm:grid-cols-3">{["List harvest", "Find demand", "Deliver fresh"].map((item, index) => <div key={item} className="border-t border-white/30 pt-3"><span className="text-amber-200">0{index + 1}</span><p className="mt-1 font-semibold">{item}</p></div>)}</div></div></div></div></section>
    <section id="for-buyers" className="bg-leaf-50 py-16 text-center"><p className="eyebrow">Ready when you are</p><h2 className="mx-auto mt-3 max-w-2xl text-3xl font-semibold tracking-tight text-leaf-900 sm:text-4xl">Bring more value to every link in the food chain.</h2><Button className="mt-7">Get started</Button></section><SiteFooter />
  </main>;
}
